name: Docker Image CI
on:
  schedule:
  - cron: "0 4 * * 1"   # 4 AM UTC on Monday
  push:
    paths-ignore:
    - LICENSE
    - README.md
    branches:
    - master

jobs:
  build:
    name: PHP ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["5.5", "5.6", "7.0", "7.1", "7.2", "7.3"]
    steps:
    - uses: actions/checkout@v1
    - run: ./scripts/build.sh --push
      env:
        VERSION_LIST: ${{ matrix.php_version }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
