name: Docker Image CI
on:
  schedule:
  - cron: "0 4 * * 1"   # 4 AM UTC on Monday
  push:
    paths-ignore:
    - LICENSE
    - README.md
    branches:
    - master
    - php74

jobs:
  php74-build:
    name: PHP 7.4 Build
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    # Some builds fail with the following error; seems to be due to first encountering a
    # timeout on connect to :443 on the IPv4 address, resulting in then trying the IPv6
    # curl: (7) Failed to connect to 2a02:cb40:200::1ad: Cannot assign requested address
    - name: Download php74 sources
      run: |
        set -eux
        mkdir -p ${GITHUB_WORKSPACE}/php74-master
        for FILE_NAME in php-7.4.5.tar.xz php-7.4.5.tar.xz.asc; do
          curl --connect-timeout 10 --retry 30 --ipv4 \
            -vLo ${GITHUB_WORKSPACE}/php74-master/$FILE_NAME \
            https://www.php.net/distributions/$FILE_NAME
        done

    - name: Build libzip1
      run: ./scripts/php74-build.sh
      env:
        PKG_LIST: iusrepo/libzip1

    - name: Build oniguruma6
      run: ./scripts/php74-build.sh
      env:
        PKG_LIST: kelnei/oniguruma6

    - name: Build php74
      run: ./scripts/php74-build.sh
      env:
        PKG_LIST: davidalger/php74

    - name: Build pecl extensions
      run: ./scripts/php74-build.sh
      env:
        PKG_LIST: >-
          kelnei/php74-pecl-apcu
          kelnei/php74-pecl-igbinary
          kelnei/php74-pecl-msgpack
          kelnei/php74-pecl-redis
          davidalger/php74-pecl-amqp
          davidalger/php74-pecl-imagick
          davidalger/php74-pecl-xdebug
          davidalger/php74-pecl-zip

    - name: Build jq
      run: ./scripts/php74-build.sh
      env:
        PKG_LIST: davidalger/jq

    - name: Upload php74
      uses: actions/upload-artifact@v1
      with:
        name: php74
        path: rpmbuild/RPMS

    - name: Upload php74-src
      uses: actions/upload-artifact@v1
      with:
        name: php74-src
        path: rpmbuild/SRPMS

  php74:
    name: PHP 7.4
    runs-on: ubuntu-latest
    needs:
    - php74-build
    steps:
    - uses: actions/checkout@v1

    - name: Download php74
      uses: actions/download-artifact@v1
      with:
        name: php74
        path: cli/php7.4/php74

    - name: Download php74-src
      uses: actions/download-artifact@v1
      with:
        name: php74-src
        path: cli/php7.4/php74-src

    - run: ./scripts/build.sh --push
      env:
        VERSION_LIST: "7.4"
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
